/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 headphones.gltf 
Author: Ankledot (https://sketchfab.com/Ankledot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-skullcandy-crusher-wireless-4e902017e4624547b440da0a6658a689
Title: Headphones Skullcandy Crusher Wireless
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/headphones/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Skullcandy_Crusher_M_Skullcandy_Crusher_0.geometry} material={materials.M_Skullcandy_Crusher} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/headphones/scene.gltf')
