/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 purse.gltf 
Author: vishnevsky.yaroslav (https://sketchfab.com/vishnevsky.yaroslav)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purse-8b0c27db69f34cc3b2242b946e96a384
Title: Purse
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/purse/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="80b9395fffaa4da4936bab834e908cf9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Torus001" position={[62.849, -37.726, -75.438]} rotation={[-1.484, 0, 0]} scale={1.256}>
                  <mesh name="Torus001_defaultMat_0" geometry={nodes.Torus001_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="Torus002" position={[-67.146, -37.727, -75.438]} rotation={[-1.484, 0, 0]} scale={1.256}>
                  <mesh name="Torus002_defaultMat_0" geometry={nodes.Torus002_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="krishka" position={[2.306, -108.337, 45.698]} rotation={[Math.PI, 0, Math.PI]} scale={[1.008, 0.977, 1]}>
                  <mesh name="krishka_default_0" geometry={nodes.krishka_default_0.geometry} material={materials['default']} />
                </group>
                <group name="Torus003" position={[62.849, -57.492, -22.211]} rotation={[-Math.PI / 2, 0, 0]} scale={1.256}>
                  <mesh name="Torus003_defaultMat_0" geometry={nodes.Torus003_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="Torus004" position={[-67.339, -57.492, -22.211]} rotation={[-Math.PI / 2, 0, 0]} scale={1.256}>
                  <mesh name="Torus004_defaultMat_0" geometry={nodes.Torus004_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="zamok" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="zamok_defaultMat_0" geometry={nodes.zamok_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="logo1" position={[0, 0, -2.378]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="logo1_defaultMat_0" geometry={nodes.logo1_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="logo2" position={[0, 0, -2.378]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="logo2_defaultMat_0" geometry={nodes.logo2_defaultMat_0.geometry} material={materials.defaultMat} />
                </group>
                <group name="cep" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="cep_defaultMat_0" geometry={nodes.cep_defaultMat_0.geometry} material={materials.defaultMat} />
                  <mesh name="cep_defaultMat_0_1" geometry={nodes.cep_defaultMat_0_1.geometry} material={materials.defaultMat} />
                </group>
                <group name="remen" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="remen_02___Default_0" geometry={nodes.remen_02___Default_0.geometry} material={materials['02___Default']} />
                </group>
                <group name="front" position={[7.639, -25.575, 219.602]} scale={[1.096, 1, 1]}>
                  <mesh name="front_default_0" geometry={nodes.front_default_0.geometry} material={materials['default']} />
                </group>
                <group name="dnishe" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="dnishe_default_0" geometry={nodes.dnishe_default_0.geometry} material={materials['default']} />
                </group>
                <group name="karman001" position={[0, 0, 0.788]} rotation={[-1.615, 0, 0]}>
                  <mesh name="karman001_default_0" geometry={nodes.karman001_default_0.geometry} material={materials['default']} />
                </group>
                <group name="shov02" position={[0, 0, 1.085]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="shov02_07_-_Default_0" geometry={nodes['shov02_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  <mesh name="shov02_07_-_Default_0_1" geometry={nodes['shov02_07_-_Default_0_1'].geometry} material={materials['07_-_Default']} />
                  <mesh name="shov02_07_-_Default_0_2" geometry={nodes['shov02_07_-_Default_0_2'].geometry} material={materials['07_-_Default']} />
                </group>
                <group name="shovkrishka" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="shovkrishka_07_-_Default_0" geometry={nodes['shovkrishka_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  <mesh name="shovkrishka_07_-_Default_0_1" geometry={nodes['shovkrishka_07_-_Default_0_1'].geometry} material={materials['07_-_Default']} />
                  <mesh name="shovkrishka_07_-_Default_0_2" geometry={nodes['shovkrishka_07_-_Default_0_2'].geometry} material={materials['07_-_Default']} />
                  <mesh name="shovkrishka_07_-_Default_0_3" geometry={nodes['shovkrishka_07_-_Default_0_3'].geometry} material={materials['07_-_Default']} />
                </group>
                <group name="shovfront" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="shovfront_07_-_Default_0" geometry={nodes['shovfront_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  <mesh name="shovfront_07_-_Default_0_1" geometry={nodes['shovfront_07_-_Default_0_1'].geometry} material={materials['07_-_Default']} />
                </group>
                <group name="Group15825" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Group15825_07_-_Default_0" geometry={nodes['Group15825_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  <mesh name="Group15825_07_-_Default_0_1" geometry={nodes['Group15825_07_-_Default_0_1'].geometry} material={materials['07_-_Default']} />
                  <mesh name="Group15825_07_-_Default_0_2" geometry={nodes['Group15825_07_-_Default_0_2'].geometry} material={materials['07_-_Default']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/purse/scene.gltf')
