/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shirt.gltf 
Author: eigenscene (https://sketchfab.com/eigenscene)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shirt-745d0d185b49405694ef4e16cf78e224
Title: Shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./shirt/shirt.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Shirt00_1Button_FRONT} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Shirt00_1Material4782} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Shirt00_1Material4782} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Shirt00_1Material4782} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Shirt00_1Material4782} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Shirt00_1Material4782} />
      </group>
    </group>
  )
}

useGLTF.preload('./shirt/shirt.gltf')
