/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 t_hoddie.gltf 
Author: harb-ayyad (https://sketchfab.com/harb-ayyad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-hoodie-3d-model-fd8d10eb5f5748e581ca6bd0db2abcce
Title: t shirt hoodie 3d model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/t_shirt_hoddie/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.01, -0.2, 0.065]} rotation={[1.595, -0.05, 0.012]} scale={0.055}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/t_shirt_hoddie/scene.gltf')
